export default{
    products:[
        {
            di:1,
            name:'CPU',
            brand:'Intel',
            price:3000,
            rating:4.5,
            numStock:100,
            numReview:10,
            image:'/images/p1.jpg'
        },

        {
            di:2,
            name:'RAM',
            brand:'Kington',
            price:1000,
            rating:3.5,
            numStock:50,
            numReview:20,
            image:'/images/p2.jpg'
        },

        {
            di:3,
            name:'VGA',
            brand:'nvidia',
            price:1000,
            rating:3.5,
            numStock:50,
            numReview:20,
            image:'/images/p3.jpg'
        },
        {
            di:4,
            name:'power supply',
            brand:'Kington',
            price:1000,
            rating:3.5,
            numStock:50,
            numReview:20,
            image:'/images/p4.jpg'
        },
        {
            di:5,
            name:'RAM',
            brand:'Kington',
            price:1000,
            rating:3.5,
            numStock:50,
            numReview:20,
            image:'/images/p2.jpg'
        },
        {
            di:6,
            name:'RAM',
            brand:'Kington',
            price:1000,
            rating:3.5,
            numStock:50,
            numReview:20,
            image:'/images/p2.jpg'
        }

    ]
}